version: "3.9"
services:
  client:
    container_name: frontend-cms
    build:
      context: ../frontend-admin-cms
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - mern-stack
    volumes:
      - ./src:/usr/app/src
    depends_on:
      - api
    stdin_open: true
    tty: true

  api:
    container_name: api-cms
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    networks:
      - mern-stack
    volumes:
      - ./src:/usr/app/src
    depends_on:
      - db

  db:
    image: mongo
    container_name: mongo-db
    ports:
      - 27017:27017
    networks:
      - mern-stack
    volumes:
      - mongo-data:/data/db

networks:
  mern-stack:
    driver: bridge

volumes:
  mongo-data:
    driver: local
