### root domain test
GET http://localhost:8000


### Admin API ###

###get Admin API
GET http://localhost:8000/api/v1/admin

###post Admin API
POST  http://localhost:8000/api/v1/admin
Content-Type: application/json

{
"fName": "admin",
"lName": "admin",
"email": "admin@yahoo.com",
"phone": "1234567890",
"address": "sydney",
"dob": "1990-09-14",
"password": "admin"
}

###update Admin API
PATCH http://localhost:8000/api/v1/admin