### root domain test
GET http://localhost:8000


### Admin API ###

###get Admin API
GET http://localhost:8000/api/v1/admin

###post Admin API
POST  http://localhost:8000/api/v1/admin
Content-Type: application/json

{
"fName": "admin",
"lName": "admin",
"email": "123@yahoo.com",
"phone": "1234567890",
"address": "sydney",
"dob": "1990-09-14",
"password": "admin"
}

###post Admin email verification API
POST  http://localhost:8000/api/v1/admin/email-verification
Content-Type: application/json

{
"email": "123@yahoo.com",
"emailValidationCode": "280e4bb4-dfdd-4cad-b79a-641e3e32b258"

}

### admin Login API
POST  http://localhost:8000/api/v1/admin/login
Content-Type: application/json

{
"email": "123@yahoo.com",
"password": "1234567890"

}

###update Admin API
PATCH http://localhost:8000/api/v1/admin



# ========== Category Section ===========

### Post new category

POST http://localhost:8000/api/v1/category
Content-Type: application/json

{
    "parentCat": "",
    "catName": "bench"
}

### get all active categories
GET http://localhost:8000/api/v1/category

### update status of a category
PATCH  http://localhost:8000/api/v1/category
Content-Type: application/json

{
    "_id": "62a7dbd7e7e3d882b393ac92",
    "status": "active"
}


# ======== Product Section =========

### Post product
POST http://localhost:8000/api/v1/products
Content-Type: application/json

{
"name": "Merida Big 200",
"sku": "MB-200",
"description": "Mountain bike - hardtail",
"qty": 100,
"price": 1000,
"salesPrice": 0,
"salesDate": null
}